---
- name: Update readme
  ansible.builtin.blockinfile:
    path: "{{ r_tempfile['path'] }}/{{ outer_item }}/roles/{{ item }}/README.md"
    prepend_newline: true
    block: |
      ---
      layout: default
      ---
  loop: "{{ lookup('ansible.builtin.fileglob', '{{ r_tempfile.path }}/{{ outer_item }}/roles/', wantlist=True) }}"

- name: Copy and rename readme
  ansible.builtin.copy:
    remote_src: "{{ r_tempfile['path'] }}/{{ outer_item }}/roles/{{ item }}/README.md"
    dest: "../_collections/{{ outer_item }}/{{ item }}.html"
    mode: "0644"
  loop: "{{ lookup('ansible.builtin.fileglob', '{{ r_tempfile.path }}/{{ outer_item }}/roles/', wantlist=True) }}"
...
