---
- name: Generate index
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Get list of files controller_config
      ansible.builtin.find:
        path: ../_collections/controller_configuration
        file_type: file
        patterns: '*.md'
      register: r_controller_config

    - name: Set file names controller_config
      ansible.builtin.set_fact:
        controller_config: "{{ controller_config | default([]) + [item | ansible.builtin.basename] }}"
      loop: "{{ r_controller_config['files'] | map(attribute='path') | flatten }}"

    - name: Get list of files galaxy_collection
      ansible.builtin.find:
        path: ../_collections/galaxy_collection
        file_type: file
        patterns: '*.md'
      register: r_galaxy_collection

    - name: Set file names galaxy_collection
      ansible.builtin.set_fact:
        galaxy_collection: "{{ galaxy_collection | default([]) + [item | ansible.builtin.basename] }}"
      loop: "{{ r_galaxy_collection['files'] | map(attribute='path') | flatten }}"

    - name: Get list of files eda_config
      ansible.builtin.find:
        path: ../_collections/eda_configuration
        file_type: file
        patterns: '*.md'
      register: r_eda_config

    - name: Set file names eda_config
      ansible.builtin.set_fact:
        eda_config: "{{ eda_config | default([]) + [item | ansible.builtin.basename] }}"
      loop: "{{ r_eda_config['files'] | map(attribute='path') | flatten }}"

    - name: Get list of files aap_utilities
      ansible.builtin.find:
        path: ../_collections/aap_utilities
        file_type: file
        patterns: '*.md'
      register: r_aap_utilities

    - name: Set file names aap_utilities
      ansible.builtin.set_fact:
        aap_utilities: "{{ aap_utilities | default([]) + [item | ansible.builtin.basename] }}"
      loop: "{{ r_aap_utilities['files'] | map(attribute='path') | flatten }}"

    - name: Get list of files ee_utilities
      ansible.builtin.find:
        path: ../_collections/ee_utilities
        file_type: file
        patterns: '*.md'
      register: r_ee_utilities

    - name: Set file names ee_utilities
      ansible.builtin.set_fact:
        ee_utilities: "{{ ee_utilities | default([]) + [item | ansible.builtin.basename] }}"
      loop: "{{ r_ee_utilities['files'] | map(attribute='path') | flatten }}"

    - name: Generate index template
      ansible.builtin.template:
        src: index.md.j2
        dest: ../index.md
        mode: "0644"
...
