title: "AAP Configuration as Code Docs"
url: "https://djdanielsson.github.io/aap_config_as_code_docs/"
remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-relative-links
collections:
  collections:
    output: true